---

AllCops:
  TargetRubyVersion: 2.3

Metrics/BlockLength:
  Exclude:
    - 'cds.gemspec'

Metrics/LineLength:
  Max: 108
  Details: >-
    Long lines require scrolling left/right when reviewing in GitHub. Keep lines below
    108 characters to avoid this. Be kind to your fellow reviewers.
  Exclude:
    - 'cds.gemspec'
    - 'test/dummy_rails/config/initializers/secret_token.rb'
