# frozen_string_literal: true

source 'https://rubygems.org'

# rubocop:disable Bundler/OrderedGems
gem 'pry'
gem 'sass', '~> 3.4'
gem 'jekyll', '3.7.0'
gem 'bourbon', '~> 4.3', '<= 5'

group :jekyll_plugins do
  gem 'jekyll-assets'
  gem 'certify_design_system', path: File.expand_path('../../../', __FILE__)
end
# rubocop:enable Bundler/OrderedGems
